import LocalizedStrings from 'react-native-localization';

export default { 
    Strings : new LocalizedStrings({
        en: {
            dachon:"Selected Song",
            baihat:"Song",
            baihot:"Hot Song",
            casy:"Singer",
            tl:"Song genre",
            online:"Music online",
            noSong:"There are no songs.",
            notFound:"No songs found.",
            noSinger:"There are no singers.",
            notFoundSinger:"No singers found.",
            notConnect:"Not connected to the Wifi Karaoke Box.",
            lostConnect:"Lost connection with Wifi Karaoke Box.",
            tim:"Search ...",
            tukhoa:"Hot Keywords",
            channel:"Channels",
            playNow:"Sing now",
            uutien:"Priority",
            auto:"Auto play",
            addAuto:"Added the song auto play.",
            removeAuto:"Removed the song auto play.",
            all:"All",
            male:"Male",
            female:"Female",
            band:"Band",
            onlMessage:"This function not now",
            
            effect:{
                huyt:"Whistle",
                kiss:"Kiss",
                smile:"Laugh",
                horeo:"Shouting",
                diem:"Score",
                votay:"Clap",
                rose:"Give flowers",
                like:"Like"
            },
            theloai:{
                remix:"DJ Hot",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIETNAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THAI-LAO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Vietnamese",
                en:"English",
                cn:"Chinese",
                jp:"Japanese",
                kr:"Korean"
            },
            chuatai:"Undownloaded",
            baichuatai:"Undownloaded Song",
            dangtai:"Downloading",
            baidangtai:"Downloading Song",
            usb:"USB Song",
            ngon:"Language",
            caidat:"Setting",
            mk:"Password",
            nmk:"Enter password",
            remove: "Erase",
            admin : {
                chuchay:"Title runs",
                auto:"Auto play",
                video:"Video output",
                matkhau:"Set Password Admin",
                wifi:"Wifi settings",
                lan:"Setting up Lan",
                wlan:"Setting up Wlan",
                domain:"Sever adress",
                san:"Scan song",
                confirm:"Confirm!",
                scanMsg1:"Are you sure you want to scan song?",
                scanMsg2:"Karaoke Box is scanning song ...",
                data:"Update data",
                dataMsg1:"Are you sure you want to update data?",
                dataMsg2:"Karaoke Box is updading data...",
                restart:"Restart",
                restartMsg1:"Are you sure you want to restart the KTV?",
                restartMsg2:"Karaoke Box is restarting  ...",
                tatmay:"Shutdown",
                tmMsg1:"Are you sure you want to turn off the KTV?",
                tmMsg2:"Karaoke is off ...",
                ok:"OK",
                cancel:"Cancel",
                save:"Save",
                updateSuccess : "Update successful!",
                updateError : "Error!update failed.",
                mkc: "Enter old password",
                mkn: "Enter your new password",
                mkr: "Re-enter password",
                hdm: "Enter server address",
            },
            
        },
        vn:{
            dachon:"Bài đã chọn",
            baihat:"Bài hát",
            baihot:"Bài hot",
            casy:"Ca sỹ",
            tl:"Thể loại",
            online:"Nhạc Online",
            noSong:"Không có bài hát nào.",
            notFound:"Không tìm thấy bài hát nào.",
            noSinger:"Không có ca sỹ nào.",
            notFoundSinger:"Không tìm thấy ca sỹ nào.",
            notConnect:"Chưa kết nối Wifi đầu Karaoke.",
            lostConnect:"Mất kết nối Wifi đầu Karaoke.",
            tim:"Tìm kiếm ...",
            tukhoa:"Từ khóa Hot",
            channel:"Kênh",
            playNow:"Hát ngay",
            uutien:"Ưu tiên",
            auto:"Bài tự động",
            addAuto:"Đã thêm bài tự động.",
            removeAuto:"Đã xóa bài tự động.",
            all:"Tất cả",
            male:"Nam ca sỹ",
            female:"Nữ ca sỹ",
            band:"Nhóm nhạc",
            onlMessage:"Chức năng này đang được xây dựng!",
            
            effect:{
                huyt:"Huýt Sáo",
                kiss:"Nụ Hôn",
                smile:"Cười",
                horeo:"Hò Reo",
                diem:"Chấm Điểm",
                votay:"Vỗ Tay",
                rose:"Tặng Hoa",
                like:"Triệu Like"
            },
            theloai:{
                remix:"DJ Hot",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIỆT NAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THÁI-LÀO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Tiếng Việt",
                en:"Tiếng Anh",
                cn:"Tiếng Trung",
                jp:"Tiếng Nhật",
                kr:"Tiếng Hàn"
            },
            chuatai:"Chưa tải",
            baichuatai:"Bài chưa tải",
            dangtai:"Đang tải",
            baidangtai:"Bài đang tải",
            usb:"Bài USB",
            ngon:"Ngôn ngữ",
            caidat:"Cài đặt",
            mk:"Mật khẩu",
            nmk:"Nhập Mật Khẩu",
            remove: "Xóa",
            admin : {
                chuchay:"Tiêu đề chạy",
                auto:"Bài tự động",
                video:"Ngõ ra Video",
                matkhau:"Đặt mật khẩu Admin",
                wifi:"Cài đặt Wifi",
                lan:"Thiết lập mạng Lan",
                wlan:"Thiết lập mạng Wlan",
                domain:"Địa chỉ máy chủ",
                san:"Quét nhạc",
                confirm:"Xác nhận!",
                scanMsg1:"Bạn thực sự muốn quét nhạc?",
                scanMsg2:"Đầu karaoke đang quét nhạc ...",
                data:"Cập nhật dữ liệu",
                dataMsg1:"Bạn thực sự muốn cập nhật dữ liệu?",
                dataMsg2:"Đầu karaoke đang cập nhật dữ liệu ...",
                restart:"Khởi động lại",
                restartMsg1:"Bạn thực sự muốn khởi động đầu karaoke?",
                restartMsg2:"Đầu karaoke đang khởi động ...",
                tatmay:"Tắt máy",
                tmMsg1:"Bạn thực sự muốn tắt đầu karaoke?",
                tmMsg2:"Đầu karaoke đang tắt ...",
                ok:"Đồng ý",
                cancel:"Hủy",
                save:"Lưu lại",
                updateSuccess : "Cập nhật thành công!",
                updateError : "Lỗi!: Cập nhật thất bại.",
                mkc: "Nhập mật khẩu cũ",
                mkn: "Nhập mật khẩu mới",
                mkr: "Nhập lại mật khẩu",
                hdm: "Nhập địa chỉ máy chủ",
            },
        },
        cn: {
            dachon:"精选歌曲",
            baihat:"歌曲",
            baihot:"热门歌曲",
            casy:"歌手",
            tl:"歌曲流派",
            online:"音乐在线",
            noSong:"没有歌.",
            notFound:"找不到歌曲.",
            noSinger:"没有歌手.",
            notFoundSinger:"没有找到歌手.",
            notConnect:"没有连接到Wifi卡拉OK盒.",
            lostConnect:"丢失了与Wifi卡拉OK盒的连接.",
            tim:"搜索 ...",
            tukhoa:"热门关键词",
            channel:"通道",
            playNow:"现在唱歌",
            uutien:"优先",
            auto:"自动播放",
            addAuto:"添加了歌曲自动播放。",
            removeAuto:"删除了歌曲自动播放。",
            all:"所有",
            male:"男",
            female:"女",
            band:"带",
            onlMessage:"这个功能现在不行!",
            
            effect:{
                huyt:"哨",
                kiss:"吻",
                smile:"笑",
                horeo:"呐喊",
                diem:"得分了",
                votay:"拍",
                rose:"送花",
                like:"喜欢"
            },
            theloai:{
                remix:"DJ Hot",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"热",
                vn:"越南",
                en:"英语",
                cn:"中文",
                jp:"日本",
                kr:"KOREAN",
                tw:"台湾",
                hk:"HONGKHONG",
                ma:"马来西亚",
                lao:"泰老",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"越南",
                en:"英语",
                cn:"中文",
                jp:"日本",
                kr:"朝鲜的"
            },
            chuatai:"删除下载",
            baichuatai:"下载歌曲",
            dangtai:"下载",
            baidangtai:"正在下载歌曲",
            usb:"USB歌曲",
            ngon:"语言",
            caidat:"设置",
            mk:"密码",
            nmk:"输入密码",
            remove: "抹去",
            admin : {
                chuchay:"标题运行",
                auto:"自动播放",
                video:"视频输出",
                matkhau:"设置密码管理员",
                wifi:"无线网络设置",
                lan:"设置Lan",
                wlan:"设置Wlan",
                domain:"Sever地址",
                san:"扫描歌曲",
                confirm:"确认！",
                scanMsg1:"你确定要扫描歌曲吗?",
                scanMsg2:"卡拉OK正在扫描歌曲 ...",
                data:"更新数据",
                dataMsg1:"您确定要更新数据吗?",
                dataMsg2:"卡拉OK盒是更新数据 ...",
                restart:"重新开始",
                restartMsg1:"你确定要重启KTV吗?",
                restartMsg2:"卡拉OK正在重启 ...",
                tatmay:"关掉",
                tmMsg1:"你确定要关闭KTV吗？",
                tmMsg2:"卡拉OK已关闭 ...",
                ok:"好",
                cancel:"取消",
                save:"保存",
                updateSuccess : "更新成功!",
                updateError : "错误！更新失败.",
                mkc: "输入旧密码",
                mkn: "输入新密码",
                mkr: "重新输入密码",
                hdm: "输入服务器地址",
            },
        },
        jp: {
            dachon:"選択した曲",
            baihat:"曲",
            baihot:"顕著な歌",
            casy:"歌手",
            tl:"曲のジャンル",
            online:"音楽オンライン",
            noSong:"歌なし.",
            notFound:"曲が見つかりませんでした.",
            noSinger:"歌手はいません.",
            notFoundSinger:"歌手が見つかりませんでした.",
            notConnect:"Wifiカラオケボックスに接続されていません.",
            lostConnect:"Wifiカラオケボックスへの接続が失われました.",
            tim:"サーチ ...",
            tukhoa:"注目キーワード",
            channel:"チャンネル",
            playNow:"今すぐ歌う",
            uutien:"優先度",
            auto:"自動再生",
            addAuto:"曲の自動再生が追加されました。",
            removeAuto:"曲の自動再生を削除しました。",
            all:"すべて",
            male:"男性",
            female:"女性",
            band:"バンド",
            onlMessage:"この機能は今ではありません!",
            
            effect:{
                huyt:"ホイッスル",
                kiss:"キッス",
                smile:"笑い",
                horeo:"叫ぶ",
                diem:"スコア",
                votay:"拍手",
                rose:"花を与える",
                like:"好き"
            },
            theloai:{
                remix:"DJ Hot",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            
            lanTab :{
                hot:"ホット",
                vn:"ベトナム",
                en:"英語",
                cn:"中国語",
                jp:"日本人",
                kr:"韓国語",
                tw:"台湾",
                hk:"香港",
                ma:"マレーシア",
                lao:"サイロ",
                ca:"カンブリア"
            },
            lan:{
                vn:"ベトナム語",
                en:"英語",
                cn:"中国語",
                jp:"日本人",
                kr:"韓国語"
            },
            chuatai:"ダウンロード",
            baichuatai:"曲のダウンロードを停止する",
            dangtai:"ダウンロード",
            baidangtai:"曲をダウンロードする",
            usb:"USBソング",
            ngon:"言語",
            caidat:"設定",
            mk:"パスワード",
            nmk:"パスワードを入力する",
            remove: "削除",
            admin : {
                chuchay:"タイトルラン",
                auto:"自動再生",
                video:"ビデオ出力",
                matkhau:"パスワード管理の設定",
                wifi:"Wi-Fi設定",
                lan:"Lanの設定",
                wlan:"Wlanの設定",
                domain:"サーバーアドレス",
                san:"スキャン曲",
                confirm:"確認してください！",
                scanMsg1:"あなたは曲をスキャンしてもよろしいですか？",
                scanMsg2:"カラオケはスキャン曲です ...",
                data:"データの更新",
                dataMsg1:"データを更新してもよろしいですか？",
                dataMsg2:"カラオケボックスはデータ更新中です ...",
                restart:"再起動",
                restartMsg1:"KTVを再起動してもよろしいですか？",
                restartMsg2:"カラオケが再開しています ...",
                tatmay:"シャットダウン",
                tmMsg1:"あなたはKTVをオフにしたいですか？",
                tmMsg2:"カラオケはオフです ...",
                ok:"OK",
                cancel:"キャンセル",
                save:"保存する",
                updateSuccess : "更新に成功！",
                updateError : "エラー！更新に失敗しました.",
                mkc: "古いパスワードを入力",
                mkn: "新しいパスワードを入力してください",
                mkr: "パスワード再入力",
                hdm: "サーバーアドレスを入力してください",
            },
        },
        kr: {
            dachon:"선택된 노래",
            baihat:"노래들",
            baihot:"핫 노래",
            casy:"가수",
            tl:"노래 장르",
            online:"음악 온라인",
            noSong:"노래 없음.",
            notFound:"노래 없음.",
            noSinger:"가수가 없다.",
            notFoundSinger:"가수가 없습니다.",
            notConnect:"Wifi 노래방에 연결되지 않았습니다.",
            lostConnect:"Wifi Karaoke Box에 대한 연결이 끊어졌습니다.",
            tim:"수색 ...",
            tukhoa:"T인기 키워드",
            channel:"지금 노래하기",
            playNow:"우선 순위",
            uutien:"자동 재생",
            auto:"자동 재생",
            addAuto:"노래 자동 재생을 추가했습니다.",
            removeAuto:"노래 자동 재생을 삭제했습니다.",
            all:"모든",
            male:"남성",
            female:"여자",
            band:"밴드",
            onlMessage:"지금은이 기능이 없습니다.",
            
            effect:{
                huyt:"휘파람",
                kiss:"키스",
                smile:"웃음",
                horeo:"외침",
                diem:"점수",
                votay:"박수",
                rose:"꽃을주세요",
                like:"처럼"
            },
            theloai:{
                remix:"DJ Hot",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"뜨거운",
                vn:"베트남",
                en:"영어",
                cn:"중국말",
                jp:"일본어",
                kr:"한국어",
                tw:"대만",
                hk:"홍콩",
                ma:"말레이시아",
                lao:"타이 라오",
                ca:"캠 푸시아"
            },
            lan:{
                vn:"베트남 사람",
                en:"영어",
                cn:"중국말",
                jp:"일본어",
                kr:"한국어"
            },
            chuatai:"다운로드되지 않음",
            baichuatai:"노래가 다운로드되지 않았습니다.",
            dangtai:"다운로드 중",
            baidangtai:"노래 다운로드 중",
            usb:"USB 노래",
            ngon:"언어",
            caidat:"환경",
            mk:"암호",
            nmk:"암호를 입력",
            remove: "삭제",
            admin : {
                chuchay:"제목 실행",
                auto:"자동 재생",
                video:"비디오 출력",
                matkhau:"비밀번호 관리 설정",
                wifi:"Wi-Fi 설정",
                lan:"Lan 설정하기",
                wlan:"무선 랜 설정",
                domain:"서버 주소",
                san:"노래 검색",
                confirm:"확인!",
                scanMsg1:"노래를 스캔 하시겠습니까?",
                scanMsg2:"노래방 스캔 노래입니다 ...",
                data:"데이터 업데이트",
                dataMsg1:"데이터를 업데이트 하시겠습니까?",
                dataMsg2:"가라오케 박스는 데이터 업데이트 중입니다...",
                restart:"재시작",
                restartMsg1:"KTV를 다시 시작 하시겠습니까?",
                restartMsg2:"노래방이 다시 시작됩니다 ...",
                tatmay:"일시 휴업",
                tmMsg1:"KTV를 끄시겠습니까?",
                tmMsg2:"노래방이 꺼져있다 ...",
                ok:"승인",
                cancel:"취소",
                save:"구하다",
                updateSuccess : "업데이트가 성공적으로 완료되었습니다.",
                updateError : "오류! 업데이트하지 못했습니다.",
                mkc: "이전 암호 입력",
                mkn: "새 암호를 입력하십시오",
                mkr: "비밀번호를 다시 입력하세요",
                hdm: "서버 주소 입력",
            },
        }
    })

}