import LocalizedStrings from 'react-native-localization';

export default { 
    Strings : new LocalizedStrings({
        en: {
            dachon:"Bài đã chọn",
            baihat:"Bài hát",
            baihot:"Bài hot",
            casy:"Ca sỹ",
            tl:"Thể loại",
            online:"Nhạc Online",
            noSong:"Không có bài hát.",
            notFound:"Không tìm thấy bài hát.",
            noSinger:"Không có ca sỹ.",
            notFoundSinger:"Không tìm thấy ca sỹ.",
            notConnect:"Chưa kết nối Wifi đầu Karaoke.",
            lostConnect:"Mất kết nối Wifi đầu Karaoke.",
            tim:"Tìm kiếm ...",
            tukhoa:"Từ khóa Hot",
            channel:"Kênh",
            playNow:"Hát ngay",
            uutien:"Ưu tiên",
            auto:"Bài tự động",
            addAuto:"Đã thêm bài tự động.",
            removeAuto:"Đã xóa bài tự động.",
            all:"Tất cả",
            male:"Nam ca sỹ",
            female:"Nữ ca sỹ",
            band:"Nhóm nhạc",
            onlMessage:"Chức năng này đang được xây dựng!",
            
            effect:{
                huyt:"Huýt Sáo",
                kiss:"Nụ Hôn",
                smile:"Cười",
                horeo:"Hò Reo",
                diem:"Chấm Điểm",
                votay:"Vỗ Tay",
                rose:"Tặng Hoa",
                like:"Triệu Like"
            },
            theloai:{
                remix:"DJ Hot en",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIỆT NAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THÁI-LÀO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Tiếng Việt",
                en:"Tiếng Anh",
                cn:"Tiếng Trung",
                jp:"Tiếng Nhật",
                kr:"Tiếng Hàn"
            },
            chuatai:"Chưa tải",
            baichuatai:"Bài chưa tải",
            dangtai:"Đang tải",
            baidangtai:"Bài đang tải",
            usb:"Bài USB",
            ngon:"Ngôn ngữ",
            caidat:"Cài đặt",
            mk:"Mật khẩu",
            nmk:"Nhập Mật Khẩu",
            remove: "Xóa",
            admin : {
                chuchay:"Tiêu đề chạy",
                auto:"Bài tự động",
                video:"Ngõ ra Video",
                matkhau:"Đặt mật khẩu Admin",
                wifi:"Cài đặt Wifi",
                lan:"Thiết lập mạng Lan",
                wlan:"Thiết lập mạng Wlan",
                domain:"Địa chỉ máy chủ",
                san:"Quét nhạc",
                confirm:"Xác nhận!",
                scanMsg1:"Bạn thực sự muốn quét nhạc?",
                scanMsg2:"Đầu karaoke đang quét nhạc ...",
                data:"Cập nhật dữ liệu",
                dataMsg1:"Bạn thực sự muốn cập nhật dữ liệu?",
                dataMsg2:"Đầu karaoke đang cập nhật dữ liệu ...",
                restart:"Khởi động lại",
                restartMsg1:"Bạn thực sự muốn khởi động đầu karaoke?",
                restartMsg2:"Đầu karaoke đang khởi động ...",
                tatmay:"Tắt máy",
                tmMsg1:"Bạn thực sự muốn tắt đầu karaoke?",
                tmMsg2:"Đầu karaoke đang tắt ...",
                ok:"Đồng ý",
                cancel:"Hủy",
                save:"Lưu lại",
                updateSuccess : "Cập nhật thành công!",
                updateError : "Lỗi!: Cập nhật thất bại.",
                mkc: "Nhập mật khẩu cũ",
                mkn: "Nhập mật khẩu mới",
                mkr: "Nhập lại mật khẩu",
                hdm: "Nhập địa chỉ máy chủ",
            },
            
        },
        vn:{
            dachon:"Bài đã chọn",
            baihat:"Bài hát",
            baihot:"Bài hot",
            casy:"Ca sỹ",
            tl:"Thể loại",
            online:"Nhạc Online",
            noSong:"Không có bài hát.",
            notFound:"Không tìm thấy bài hát.",
            noSinger:"Không có ca sỹ.",
            notFoundSinger:"Không tìm thấy ca sỹ.",
            notConnect:"Chưa kết nối Wifi đầu Karaoke.",
            lostConnect:"Mất kết nối Wifi đầu Karaoke.",
            tim:"Tìm kiếm ...",
            tukhoa:"Từ khóa Hot",
            channel:"Kênh",
            playNow:"Hát ngay",
            uutien:"Ưu tiên",
            auto:"Bài tự động",
            addAuto:"Đã thêm bài tự động.",
            removeAuto:"Đã xóa bài tự động.",
            all:"Tất cả",
            male:"Nam ca sỹ",
            female:"Nữ ca sỹ",
            band:"Nhóm nhạc",
            onlMessage:"Chức năng này đang được xây dựng!",
            
            effect:{
                huyt:"Huýt Sáo",
                kiss:"Nụ Hôn",
                smile:"Cười",
                horeo:"Hò Reo",
                diem:"Chấm Điểm",
                votay:"Vỗ Tay",
                rose:"Tặng Hoa",
                like:"Triệu Like"
            },
            theloai:{
                remix:"DJ Hot en",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIỆT NAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THÁI-LÀO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Tiếng Việt",
                en:"Tiếng Anh",
                cn:"Tiếng Trung",
                jp:"Tiếng Nhật",
                kr:"Tiếng Hàn"
            },
            chuatai:"Chưa tải",
            baichuatai:"Bài chưa tải",
            dangtai:"Đang tải",
            baidangtai:"Bài đang tải",
            usb:"Bài USB",
            ngon:"Ngôn ngữ",
            caidat:"Cài đặt",
            mk:"Mật khẩu",
            nmk:"Nhập Mật Khẩu",
            remove: "Xóa",
            admin : {
                chuchay:"Tiêu đề chạy",
                auto:"Bài tự động",
                video:"Ngõ ra Video",
                matkhau:"Đặt mật khẩu Admin",
                wifi:"Cài đặt Wifi",
                lan:"Thiết lập mạng Lan",
                wlan:"Thiết lập mạng Wlan",
                domain:"Địa chỉ máy chủ",
                san:"Quét nhạc",
                confirm:"Xác nhận!",
                scanMsg1:"Bạn thực sự muốn quét nhạc?",
                scanMsg2:"Đầu karaoke đang quét nhạc ...",
                data:"Cập nhật dữ liệu",
                dataMsg1:"Bạn thực sự muốn cập nhật dữ liệu?",
                dataMsg2:"Đầu karaoke đang cập nhật dữ liệu ...",
                restart:"Khởi động lại",
                restartMsg1:"Bạn thực sự muốn khởi động đầu karaoke?",
                restartMsg2:"Đầu karaoke đang khởi động ...",
                tatmay:"Tắt máy",
                tmMsg1:"Bạn thực sự muốn tắt đầu karaoke?",
                tmMsg2:"Đầu karaoke đang tắt ...",
                ok:"Đồng ý",
                cancel:"Hủy",
                save:"Lưu lại",
                updateSuccess : "Cập nhật thành công!",
                updateError : "Lỗi!: Cập nhật thất bại.",
                mkc: "Nhập mật khẩu cũ",
                mkn: "Nhập mật khẩu mới",
                mkr: "Nhập lại mật khẩu",
                hdm: "Nhập địa chỉ máy chủ",
            },

        },
        cn: {
            dachon:"Bài đã chọn",
            baihat:"Bài hát",
            baihot:"Bài hot",
            casy:"Ca sỹ",
            tl:"Thể loại",
            online:"Nhạc Online",
            noSong:"Không có bài hát.",
            notFound:"Không tìm thấy bài hát.",
            noSinger:"Không có ca sỹ.",
            notFoundSinger:"Không tìm thấy ca sỹ.",
            notConnect:"Chưa kết nối Wifi đầu Karaoke.",
            lostConnect:"Mất kết nối Wifi đầu Karaoke.",
            tim:"Tìm kiếm ...",
            tukhoa:"Từ khóa Hot",
            channel:"Kênh",
            playNow:"Hát ngay",
            uutien:"Ưu tiên",
            auto:"Bài tự động",
            addAuto:"Đã thêm bài tự động.",
            removeAuto:"Đã xóa bài tự động.",
            all:"Tất cả",
            male:"Nam ca sỹ",
            female:"Nữ ca sỹ",
            band:"Nhóm nhạc",
            onlMessage:"Chức năng này đang được xây dựng!",
            
            effect:{
                huyt:"Huýt Sáo",
                kiss:"Nụ Hôn",
                smile:"Cười",
                horeo:"Hò Reo",
                diem:"Chấm Điểm",
                votay:"Vỗ Tay",
                rose:"Tặng Hoa",
                like:"Triệu Like"
            },
            theloai:{
                remix:"DJ Hot en",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIỆT NAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THÁI-LÀO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Tiếng Việt",
                en:"Tiếng Anh",
                cn:"Tiếng Trung",
                jp:"Tiếng Nhật",
                kr:"Tiếng Hàn"
            },
            chuatai:"Chưa tải",
            baichuatai:"Bài chưa tải",
            dangtai:"Đang tải",
            baidangtai:"Bài đang tải",
            usb:"Bài USB",
            ngon:"Ngôn ngữ",
            caidat:"Cài đặt",
            mk:"Mật khẩu",
            nmk:"Nhập Mật Khẩu",
            remove: "Xóa",
            admin : {
                chuchay:"Tiêu đề chạy",
                auto:"Bài tự động",
                video:"Ngõ ra Video",
                matkhau:"Đặt mật khẩu Admin",
                wifi:"Cài đặt Wifi",
                lan:"Thiết lập mạng Lan",
                wlan:"Thiết lập mạng Wlan",
                domain:"Địa chỉ máy chủ",
                san:"Quét nhạc",
                confirm:"Xác nhận!",
                scanMsg1:"Bạn thực sự muốn quét nhạc?",
                scanMsg2:"Đầu karaoke đang quét nhạc ...",
                data:"Cập nhật dữ liệu",
                dataMsg1:"Bạn thực sự muốn cập nhật dữ liệu?",
                dataMsg2:"Đầu karaoke đang cập nhật dữ liệu ...",
                restart:"Khởi động lại",
                restartMsg1:"Bạn thực sự muốn khởi động đầu karaoke?",
                restartMsg2:"Đầu karaoke đang khởi động ...",
                tatmay:"Tắt máy",
                tmMsg1:"Bạn thực sự muốn tắt đầu karaoke?",
                tmMsg2:"Đầu karaoke đang tắt ...",
                ok:"Đồng ý",
                cancel:"Hủy",
                save:"Lưu lại",
                updateSuccess : "Cập nhật thành công!",
                updateError : "Lỗi!: Cập nhật thất bại.",
                mkc: "Nhập mật khẩu cũ",
                mkn: "Nhập mật khẩu mới",
                mkr: "Nhập lại mật khẩu",
                hdm: "Nhập địa chỉ máy chủ",
            },
        },
        jp: {
            dachon:"Bài đã chọn",
            baihat:"Bài hát",
            baihot:"Bài hot",
            casy:"Ca sỹ",
            tl:"Thể loại",
            online:"Nhạc Online",
            noSong:"Không có bài hát.",
            notFound:"Không tìm thấy bài hát.",
            noSinger:"Không có ca sỹ.",
            notFoundSinger:"Không tìm thấy ca sỹ.",
            notConnect:"Chưa kết nối Wifi đầu Karaoke.",
            lostConnect:"Mất kết nối Wifi đầu Karaoke.",
            tim:"Tìm kiếm ...",
            tukhoa:"Từ khóa Hot",
            channel:"Kênh",
            playNow:"Hát ngay",
            uutien:"Ưu tiên",
            auto:"Bài tự động",
            addAuto:"Đã thêm bài tự động.",
            removeAuto:"Đã xóa bài tự động.",
            all:"Tất cả",
            male:"Nam ca sỹ",
            female:"Nữ ca sỹ",
            band:"Nhóm nhạc",
            onlMessage:"Chức năng này đang được xây dựng!",
            
            effect:{
                huyt:"Huýt Sáo",
                kiss:"Nụ Hôn",
                smile:"Cười",
                horeo:"Hò Reo",
                diem:"Chấm Điểm",
                votay:"Vỗ Tay",
                rose:"Tặng Hoa",
                like:"Triệu Like"
            },
            theloai:{
                remix:"DJ Hot en",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIỆT NAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THÁI-LÀO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Tiếng Việt",
                en:"Tiếng Anh",
                cn:"Tiếng Trung",
                jp:"Tiếng Nhật",
                kr:"Tiếng Hàn"
            },
            chuatai:"Chưa tải",
            baichuatai:"Bài chưa tải",
            dangtai:"Đang tải",
            baidangtai:"Bài đang tải",
            usb:"Bài USB",
            ngon:"Ngôn ngữ",
            caidat:"Cài đặt",
            mk:"Mật khẩu",
            nmk:"Nhập Mật Khẩu",
            remove: "Xóa",
            admin : {
                chuchay:"Tiêu đề chạy",
                auto:"Bài tự động",
                video:"Ngõ ra Video",
                matkhau:"Đặt mật khẩu Admin",
                wifi:"Cài đặt Wifi",
                lan:"Thiết lập mạng Lan",
                wlan:"Thiết lập mạng Wlan",
                domain:"Địa chỉ máy chủ",
                san:"Quét nhạc",
                confirm:"Xác nhận!",
                scanMsg1:"Bạn thực sự muốn quét nhạc?",
                scanMsg2:"Đầu karaoke đang quét nhạc ...",
                data:"Cập nhật dữ liệu",
                dataMsg1:"Bạn thực sự muốn cập nhật dữ liệu?",
                dataMsg2:"Đầu karaoke đang cập nhật dữ liệu ...",
                restart:"Khởi động lại",
                restartMsg1:"Bạn thực sự muốn khởi động đầu karaoke?",
                restartMsg2:"Đầu karaoke đang khởi động ...",
                tatmay:"Tắt máy",
                tmMsg1:"Bạn thực sự muốn tắt đầu karaoke?",
                tmMsg2:"Đầu karaoke đang tắt ...",
                ok:"Đồng ý",
                cancel:"Hủy",
                save:"Lưu lại",
                updateSuccess : "Cập nhật thành công!",
                updateError : "Lỗi!: Cập nhật thất bại.",
                mkc: "Nhập mật khẩu cũ",
                mkn: "Nhập mật khẩu mới",
                mkr: "Nhập lại mật khẩu",
                hdm: "Nhập địa chỉ máy chủ",
            },
        },
        kr: {
            dachon:"Bài đã chọn",
            baihat:"Bài hát",
            baihot:"Bài hot",
            casy:"Ca sỹ",
            tl:"Thể loại",
            online:"Nhạc Online",
            noSong:"Không có bài hát.",
            notFound:"Không tìm thấy bài hát.",
            noSinger:"Không có ca sỹ.",
            notFoundSinger:"Không tìm thấy ca sỹ.",
            notConnect:"Chưa kết nối Wifi đầu Karaoke.",
            lostConnect:"Mất kết nối Wifi đầu Karaoke.",
            tim:"Tìm kiếm ...",
            tukhoa:"Từ khóa Hot",
            channel:"Kênh",
            playNow:"Hát ngay",
            uutien:"Ưu tiên",
            auto:"Bài tự động",
            addAuto:"Đã thêm bài tự động.",
            removeAuto:"Đã xóa bài tự động.",
            all:"Tất cả",
            male:"Nam ca sỹ",
            female:"Nữ ca sỹ",
            band:"Nhóm nhạc",
            onlMessage:"Chức năng này đang được xây dựng!",
            
            effect:{
                huyt:"Huýt Sáo",
                kiss:"Nụ Hôn",
                smile:"Cười",
                horeo:"Hò Reo",
                diem:"Chấm Điểm",
                votay:"Vỗ Tay",
                rose:"Tặng Hoa",
                like:"Triệu Like"
            },
            theloai:{
                remix:"DJ Hot en",
                nhactre:"Nhạc Trẻ",
                nhacvang:"Nhạc Vàng",
                nhacdo:"Nhạc Đỏ",
                songca:"Song Ca",
                thieunhi:"Thiếu Nhi",
                lienkhuc:"Liên Khúc",
                sinhnhat:"Sinh Nhật",
                nhacxuan:"Nhạc Xuân",
                nhactrinh:"Nhạc Trịnh",
                cailuong:"Cải Lương",
                danca: "Dân Ca"
            },
            lanTab :{
                hot:"HOT",
                vn:"VIỆT NAM",
                en:"ENGLISH",
                cn:"CHINESE",
                jp:"JAPANESE",
                kr:"KOREAN",
                tw:"TAIWAN",
                hk:"HONGKHONG",
                ma:"MALAYSIA",
                lao:"THÁI-LÀO",
                ca:"CAMPUCHIA"
            },
            lan:{
                vn:"Tiếng Việt",
                en:"Tiếng Anh",
                cn:"Tiếng Trung",
                jp:"Tiếng Nhật",
                kr:"Tiếng Hàn"
            },
            chuatai:"Chưa tải",
            baichuatai:"Bài chưa tải",
            dangtai:"Đang tải",
            baidangtai:"Bài đang tải",
            usb:"Bài USB",
            ngon:"Ngôn ngữ",
            caidat:"Cài đặt",
            mk:"Mật khẩu",
            nmk:"Nhập Mật Khẩu",
            remove: "Xóa",
            admin : {
                chuchay:"Tiêu đề chạy",
                auto:"Bài tự động",
                video:"Ngõ ra Video",
                matkhau:"Đặt mật khẩu Admin",
                wifi:"Cài đặt Wifi",
                lan:"Thiết lập mạng Lan",
                wlan:"Thiết lập mạng Wlan",
                domain:"Địa chỉ máy chủ",
                san:"Quét nhạc",
                confirm:"Xác nhận!",
                scanMsg1:"Bạn thực sự muốn quét nhạc?",
                scanMsg2:"Đầu karaoke đang quét nhạc ...",
                data:"Cập nhật dữ liệu",
                dataMsg1:"Bạn thực sự muốn cập nhật dữ liệu?",
                dataMsg2:"Đầu karaoke đang cập nhật dữ liệu ...",
                restart:"Khởi động lại",
                restartMsg1:"Bạn thực sự muốn khởi động đầu karaoke?",
                restartMsg2:"Đầu karaoke đang khởi động ...",
                tatmay:"Tắt máy",
                tmMsg1:"Bạn thực sự muốn tắt đầu karaoke?",
                tmMsg2:"Đầu karaoke đang tắt ...",
                ok:"Đồng ý",
                cancel:"Hủy",
                save:"Lưu lại",
                updateSuccess : "Cập nhật thành công!",
                updateError : "Lỗi!: Cập nhật thất bại.",
                mkc: "Nhập mật khẩu cũ",
                mkn: "Nhập mật khẩu mới",
                mkr: "Nhập lại mật khẩu",
                hdm: "Nhập địa chỉ máy chủ",
            },
        }
    })

}